Fixed numpy typehint in compressor.py
The typehint " Tuple[Any, np.ndarray[Any, np.dtype[Any]], List[Any]]"

Was causing TypeError:

TypeError: 'numpy._DTypeMeta' object is not subscriptable

in Python 3.7.

Simplified to Tuple[Any, np.ndarray, List[Any]]